site_name: Dokumentacja Projektu

nav:
  - Strona główna: index.md
  - Python:
      - Dokumentacja: python.md
  - C++:
      - Dokumentacja: cpp.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]
        clang:
          paths: ["../src"]


markdown_extensions:
  - fenced_code
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
