name: Dokumentacja wielu systemów

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Create a clean directory for GitHub Pages
      - name: Prepare deployment directory
        run: mkdir -p gh-pages

      # --- MKDOCS ---
      - name: Set up Python for MkDocs
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies for MkDocs
        run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python

      - name: Build MkDocs documentation
        run: |
          cd my-project-docs
          mkdocs build

      - name: Move MkDocs output
        run: | 
          cd my-project-docs/
          mv site ../gh-pages/mkdocs

      # --- SPHINX ---
      - name: Set up Python for Sphinx
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies for Sphinx
        run: |
          pip install sphinx sphinx-rtd-theme

      - name: Build Sphinx documentation
        run: |
          cd my-project-docs
          make html

      - name: Move Sphinx output
        run: |
          mv my-project-docs/build/html gh-pages/sphinx

      # --- DOXYGEN ---
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Move Doxygen output
        run: mv doxygen_docs gh-pages/doxygen

      # --- DEPLOY TO GITHUB PAGES ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
