name: Dokumentacja wielu systemów

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Clean build directory
        run: |
          rm -rf build/html
          rm -rf doxygen_docs/xml

      # Create a clean directory for GitHub Pages
      - name: Prepare deployment directory
        run: mkdir -p gh-pages

      # --- MKDOCS ---
      - name: Set up Python for MkDocs
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies for MkDocs
        run: pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python

      # --- DOXYGEN ---
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      # --- SPHINX ---
      - name: Set up Python for Sphinx
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies for Sphinx
        run: |
          pip install sphinx sphinx-rtd-theme breathe sphinx-autodoc-typehints

      - name: Generate python.rst and python.md
        run: python generate_python_docs.py

      - name: Build MkDocs documentation
        run: |
          cd my-project-docs
          mkdocs build

      - name: Move MkDocs output
        run: | 
          cd my-project-docs/
          mv site ../gh-pages/mkdocs

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile 

      - name: Build Sphinx documentation
        run: make html  

      - name: Move Sphinx output
        run: mv build/html gh-pages/sphinx

      - name: Move Doxygen output
        run: mv doxygen_docs/html gh-pages/doxygen/

      # --- DEPLOY TO GITHUB PAGES ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: gh-pages